# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsosiyYonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/asosiy_yonalish/')),
            ],
            options={
                'verbose_name': 'Asosiy yo‘nalish',
                'verbose_name_plural': 'Asosiy yo‘nalishlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BizningXizmatlarEhtiyojQoplaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='bosh_sahifa/bizning_xizmatlar/')),
            ],
        ),
        migrations.CreateModel(
            name='DavolashUsuliTanlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5.0)),
                ('davomiylik', models.PositiveIntegerField(help_text='Davolash davomiyligi (kunlarda)')),
                ('narx', models.PositiveIntegerField(help_text='Davolash narxi $da')),
            ],
        ),
        migrations.CreateModel(
            name='DavolashUsuliTanlangTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HududTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hudud (tarjima)',
                'verbose_name_plural': 'Hududlar (tarjimalar)',
            },
        ),
        migrations.CreateModel(
            name='Konsultatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_raqam', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqam '+998XXXXXXXXX' formatida bo'lishi kerak (masalan: +998901234567).", regex='^\\+998\\d{9}$')])),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konsultatsiya',
                'verbose_name_plural': 'Konsultatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Natijalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/natijalar/')),
                ('statistik_raqam', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
        migrations.CreateModel(
            name='NatijalarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Natija (tarjima)',
                'verbose_name_plural': 'Natijalar (tarjimalar)',
            },
        ),
        migrations.CreateModel(
            name='YonalishAmaliyoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/yonalish_amaliyoti/')),
                ('narx', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Yonalish amaliyoti',
                'verbose_name_plural': 'Yonalish amaliyotlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YonalishAmaliyotiTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Yonalish amaliyoti (tarjima)',
                'verbose_name_plural': 'Yonalish amaliyotlari (tarjimalar)',
            },
        ),
        migrations.CreateModel(
            name='AsosiyYonalishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('yordam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.asosiyyonalish')),
            ],
            options={
                'verbose_name': 'Tibbiy yordam (tarjima)',
                'verbose_name_plural': 'Tibbiy yordamlar (tarjimalar)',
            },
        ),
        migrations.CreateModel(
            name='BizningXizmatlarEhtiyojQoplaydiTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.bizningxizmatlarehtiyojqoplaydi')),
            ],
        ),
    ]
