# Generated by Django 5.2.7 on 2025-10-18 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DavolashUsuli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Konsultatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_raqam', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqam '+998XXXXXXXXX' formatida bo'lishi kerak (masalan: +998901234567).", regex='^\\+998\\d{9}$')])),
                ('davolash_usuli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.davolashusuli')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.hudud')),
            ],
        ),
    ]
