# Generated by Django 5.2.7 on 2025-10-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizningXizmatlarEhtiyojQoplaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='bosh_sahifa/bizning_xizmatlar/')),
            ],
        ),
        migrations.CreateModel(
            name='DavolashUsuliTanlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5.0)),
                ('location', models.CharField(max_length=200)),
                ('davomiylik', models.PositiveIntegerField(help_text='Davolash davomiyligi (kunlarda)')),
                ('narx', models.PositiveIntegerField(help_text='Davolash narxi $da')),
            ],
        ),
        migrations.CreateModel(
            name='KafolatlanganArzonNarxlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/kafolatlangan_arzon_narxlar/')),
                ('narx', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Kafolatlangan arzon narx',
                'verbose_name_plural': 'Kafolatlangan arzon narxlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KopTarmoqliTibbiyYordam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/kop_tarmoqli_tibbiy_yordam/')),
            ],
            options={
                'verbose_name': 'Ko‘p tarmoqli tibbiy yordam',
                'verbose_name_plural': 'Ko‘p tarmoqli tibbiy yordamlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MashhurShifokorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='bosh_sahifa/mashhur_shifokorlar/')),
                ('rating', models.FloatField(default=5.0)),
                ('tajriba_yil', models.PositiveIntegerField()),
                ('jarrohlik_amaliyotlar_soni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Natijalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/natijalar/')),
                ('statistik_raqam', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
        migrations.CreateModel(
            name='OmmabopShifoxonalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/ommabop_shifoxonalar/')),
            ],
            options={
                'verbose_name': 'Ommabop shifoxona',
                'verbose_name_plural': 'Ommabop shifoxonalar',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='davolashusuli',
            options={'ordering': ['id'], 'verbose_name': 'Davolash usuli', 'verbose_name_plural': 'Davolash usullari'},
        ),
        migrations.AlterModelOptions(
            name='hudud',
            options={'ordering': ['id'], 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterModelOptions(
            name='konsultatsiya',
            options={'verbose_name': 'Konsultatsiya', 'verbose_name_plural': 'Konsultatsiyalar'},
        ),
        migrations.RemoveField(
            model_name='davolashusuli',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='hudud',
            name='nomi',
        ),
        migrations.CreateModel(
            name='BizningXizmatlarEhtiyojQoplaydiTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.bizningxizmatlarehtiyojqoplaydi')),
            ],
        ),
        migrations.CreateModel(
            name='DavolashUsuliTanlangTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.davolashusulitanlang')),
            ],
        ),
        migrations.AddField(
            model_name='davolashusulitanlang',
            name='doktor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.mashhurshifokorlar'),
        ),
        migrations.CreateModel(
            name='MashhurShifokorlarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('ism_familiya', models.CharField(max_length=200)),
                ('mutaxassislik', models.CharField(max_length=200)),
                ('maslahat', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.mashhurshifokorlar')),
            ],
        ),
        migrations.CreateModel(
            name='DavolashUsuliTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
                ('davolash_usuli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.davolashusuli')),
            ],
            options={
                'verbose_name': 'Davolash usuli (tarjima)',
                'verbose_name_plural': 'Davolash usullari (tarjimalar)',
                'unique_together': {('davolash_usuli', 'language')},
            },
        ),
        migrations.CreateModel(
            name='HududTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.hudud')),
            ],
            options={
                'verbose_name': 'Hudud (tarjima)',
                'verbose_name_plural': 'Hududlar (tarjimalar)',
                'unique_together': {('hudud', 'language')},
            },
        ),
        migrations.CreateModel(
            name='KafolatlanganArzonNarxlarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('narx_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.kafolatlanganarzonnarxlar')),
            ],
            options={
                'verbose_name': 'Narx (tarjima)',
                'verbose_name_plural': 'Narxlar (tarjimalar)',
                'unique_together': {('narx_obj', 'language')},
            },
        ),
        migrations.CreateModel(
            name='KopTarmoqliTibbiyYordamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('yordam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.koptarmoqlitibbiyyordam')),
            ],
            options={
                'verbose_name': 'Tibbiy yordam (tarjima)',
                'verbose_name_plural': 'Tibbiy yordamlar (tarjimalar)',
                'unique_together': {('yordam', 'language')},
            },
        ),
        migrations.CreateModel(
            name='NatijalarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('text', models.CharField(max_length=255)),
                ('natija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.natijalar')),
            ],
            options={
                'verbose_name': 'Natija (tarjima)',
                'verbose_name_plural': 'Natijalar (tarjimalar)',
                'unique_together': {('natija', 'language')},
            },
        ),
        migrations.CreateModel(
            name='OmmabopShifoxonalarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('shifoxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.ommabopshifoxonalar')),
            ],
            options={
                'verbose_name': 'Shifoxona (tarjima)',
                'verbose_name_plural': 'Shifoxonalar (tarjimalar)',
                'unique_together': {('shifoxona', 'language')},
            },
        ),
    ]
