# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
        ('shifokorlar', '0001_initial'),
        ('shifoxonalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='davolashusulitanlang',
            name='doktor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifokorlar.shifokor'),
        ),
        migrations.AddField(
            model_name='davolashusulitanlang',
            name='shifoxona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifoxonalar.shifoxona'),
        ),
        migrations.AddField(
            model_name='davolashusulitanlangtranslation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.davolashusulitanlang'),
        ),
        migrations.AddField(
            model_name='hududtranslation',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.hudud'),
        ),
        migrations.AddField(
            model_name='konsultatsiya',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.hudud'),
        ),
        migrations.AddField(
            model_name='natijalartranslation',
            name='natija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.natijalar'),
        ),
        migrations.AddField(
            model_name='yonalishamaliyoti',
            name='asosiy_yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.asosiyyonalish'),
        ),
        migrations.AddField(
            model_name='konsultatsiya',
            name='yonalish_amaliyoti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.yonalishamaliyoti'),
        ),
        migrations.AddField(
            model_name='yonalishamaliyotitranslation',
            name='narx_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bosh_sahifa.yonalishamaliyoti'),
        ),
        migrations.AlterUniqueTogether(
            name='asosiyyonalishtranslation',
            unique_together={('yordam', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='hududtranslation',
            unique_together={('hudud', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='natijalartranslation',
            unique_together={('natija', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='yonalishamaliyotitranslation',
            unique_together={('narx_obj', 'language')},
        ),
    ]
