# Generated by Django 5.2.7 on 2025-10-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0002_bizningxizmatlarehtiyojqoplaydi_davolashusulitanlang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultatsiya',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
