# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shahar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifoxonalar.davlat')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shifoxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='bosh_sahifa/ommabop_shifoxonalar/')),
                ('asosiy_yonalish', models.ManyToManyField(to='bosh_sahifa.asosiyyonalish')),
                ('shahar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifoxonalar.shahar')),
            ],
            options={
                'verbose_name': 'shifoxona',
                'verbose_name_plural': 'shifoxonalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DavlatTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shifoxonalar.davlat')),
            ],
            options={
                'verbose_name': 'Davlat (tarjima)',
                'verbose_name_plural': 'Davlatlar (tarjimalar)',
                'unique_together': {('davlat', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ShaharTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('nomi', models.CharField(max_length=100)),
                ('shahar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shifoxonalar.shahar')),
            ],
            options={
                'verbose_name': 'Shahar (tarjima)',
                'verbose_name_plural': 'Shaharlar (tarjimalar)',
                'unique_together': {('shahar', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ShifoxonaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('shifoxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shifoxonalar.shifoxona')),
            ],
            options={
                'verbose_name': 'Shifoxona (tarjima)',
                'verbose_name_plural': 'Shifoxonalar (tarjimalar)',
                'unique_together': {('shifoxona', 'language')},
            },
        ),
    ]
