# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MamnunBemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamnun', models.PositiveIntegerField()),
                ('ijobiy_foiz', models.PositiveIntegerField()),
                ('mamlakat_bemorlari', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Mamnun bemor',
                'verbose_name_plural': 'Mamnun bemorlar',
            },
        ),
        migrations.CreateModel(
            name='BemorFikri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharh_matni', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('baho', models.PositiveIntegerField(default=5)),
                ('amaliyot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.yonalishamaliyoti')),
            ],
            options={
                'verbose_name': 'Bemorlar fikri',
                'verbose_name_plural': 'Bemorlar fikrlari',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
    ]
