# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
        ('shifoxonalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifokor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='bosh_sahifa/shifokorlar/')),
                ('rating', models.FloatField(default=5.0)),
                ('tajriba_yil', models.PositiveIntegerField()),
                ('jarrohlik_amaliyotlar_soni', models.PositiveIntegerField()),
                ('rezyume', models.FileField(upload_to='bosh_sahifa/shifokorlar/rezyume/')),
                ('shifoxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifoxonalar.shifoxona')),
                ('yonalish', models.ManyToManyField(to='bosh_sahifa.asosiyyonalish')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShifokorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('ism_familiya', models.CharField(max_length=200)),
                ('maslahat', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shifokorlar.shifokor')),
            ],
            options={
                'verbose_name': 'Shifokor (tarjima)',
                'verbose_name_plural': 'Shifokorlar (tarjimalar)',
                'unique_together': {('parent', 'language')},
            },
        ),
    ]
